# Generated by Django 5.0.1 on 2024-02-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sw',
            old_name='breed',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='sw',
            name='age',
        ),
        migrations.AddField(
            model_name='sw',
            name='version',
            field=models.CharField(default='1.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='sw',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
