# Generated by Django 5.0.1 on 2024-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_breed_sw_model_remove_sw_age_sw_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(default=None)),
                ('toolsUsed', models.TextField(default=None)),
            ],
        ),
    ]
