# Generated by Django 5.0.1 on 2024-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom',
            name='toolsUsed',
        ),
        migrations.AddField(
            model_name='custom',
            name='tools_Used',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='custom',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
