# Generated by Django 5.0.1 on 2024-02-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_custom_toolsused_custom_tools_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='tools_Used',
            field=models.TextField(max_length=100),
        ),
    ]
