# Generated by Django 5.0.1 on 2024-02-06 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_custom_description_alter_custom_tools_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='sw',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.sw'),
        ),
    ]
