# Generated by Django 5.0.1 on 2024-02-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_sw_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sw',
            name='Vehicles',
            field=models.ManyToManyField(related_name='sws', to='main_app.vehicle'),
        ),
    ]
