# Generated by Django 5.0.1 on 2024-02-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_sw_vehicles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sw',
            old_name='Vehicles',
            new_name='vehicles',
        ),
    ]
